version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bxc-server
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/restart.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/health.sh
      timeout: 30
      runas: ubuntu
