name: "Coverage badge"

on:
  workflow_run:
    workflows:
      - "Lint and Test"
    types:
      - completed

jobs:
  coverage-badge:
    name: Update coverage badge
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Download artifact - code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
      - name: Parse coverage
        id: parse-coverage
        run: |
          echo "::set-output name=COVERAGE::Coverage-$(grep -m1 'strong' index.html | awk -F '>' '{print $2}' | awk '{print $1}')"
      - name: Replace badge
        run: |
          echo ${{ steps.parse-coverage.outputs.COVERAGE }}
          sed -i '2s#Coverage.*%#${{ steps.parse-coverage.outputs.COVERAGE }}#' README.md
      - name: Check for file changes
        id: check-changes
        run: |
          echo "::set-output name=CHANGES::$(git diff --quiet README.md || echo 'yes')"
      - name: Commit changes
        if: ${{ steps.check-changes.outputs.CHANGES }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update coverage badge"
      - name: Push changes
        if: ${{ steps.check-changes.outputs.CHANGES }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: ${{ github.ref }}
