name: Deploy

###############################
# Disabled deployment workflow
###############################

# on:
#   workflow_run:
#     workflows:
#       - "Lint and Test"
#     branches:
#       - main
#     types:
#       - completed

on:
  push:
    branches-ignore:
      - "**"

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    name: AWS-Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12.x"]
        app-name: ["bxc-server"]
        deploy-group: ["staging"]
        s3-bucket: ["aws-bxc-deployments"]
        s3-filename: ["staging-aws-bxc"]
    steps:
      # Checkout current repository
      - uses: actions/checkout@v2

      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies and build
      - name: Install npm dependencies
        run: npm install
      - name: Run build
        run: npm build

      # Install AWS CLI 2
      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Delete development and CI related files
      # These files are not required for production
      - name: Delete development and CI related files
        run: |
          rm -rf "awscliv2.zip" "aws"
          rm -rf "test" "node_modules" "docs"
          rm README.md

      # Deploy push to AWS S3
      - name: AWS Deploy push
        run: |
          aws deploy push \
          --application-name ${{ matrix.app-name }} \
          --description "This is a revision for the ${{ matrix.app-name }}" \
          --ignore-hidden-files \
          --s3-location s3://${{ matrix.s3-bucket }}/${{ matrix.s3-filename }}.zip \
          --source .

      # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ matrix.app-name }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name ${{ matrix.deploy-group }} \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=${{ matrix.s3-bucket }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \
