name: "Lint and Test"

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**/CODEOWNERS"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and lint
        run: |
          npm install
          npm build
          npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and test
        run: |
          npm install
          npm build
          npm test
      - name: Generate code coverage report
        run: |
          npm run test-report:gen
      - name: Upload artifact - code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/index.html
          retention-days: 1
